Run all tests and report results at the end (#117)
* Run all tests and report at the end results

This commit executes all tests and at the end
reports whole summary for each version.

Signed-off-by: Petr "Stone" Hracek <phracek@redhat.com>

* Use check_result for handling TESTSUITE_RESULT globally

Signed-off-by: Petr "Stone" Hracek <phracek@redhat.com>

* Add run_all_tests also for version 1.18

Signed-off-by: Petr "Stone" Hracek <phracek@redhat.com>

* script finishes with return value TESTSUITE_RESULT

Fixing APP_NAME which was not defined in run_all_tests
function

Signed-off-by: Petr "Stone" Hracek <phracek@redhat.com>

* check_result function returns value

check_result function returns value from command
so test function can success / fail based on the last command.

Signed-off-by: Petr "Stone" Hracek <phracek@redhat.com>

diff --git a/1.18/test/run b/1.18/test/run
--- a/1.18/test/run
+++ b/1.18/test/run
@@ -12,6 +12,21 @@ test -n "${VERSION-}" || false 'make sure $VERSION is defined'
 # TODO: Make command compatible for Mac users
 test_dir="$(readlink -zf $(dirname "${BASH_SOURCE[0]}"))"
 image_dir=$(readlink -zf ${test_dir}/..)
+test_short_summary=''
+TESTSUITE_RESULT=0
+
+TEST_LIST_APP="\
+test_s2i_usage
+test_docker_run_usage
+test_application
+test_log_output
+test_log_volume_output
+test_application_user
+test_latest_imagestreams
+"
+TEST_LIST_HOOK_APP="test_pre_init_script"
+TEST_LIST_PERL_APP="test_perl_directive"
+
 
 . $test_dir/test-lib.sh
 
@@ -81,10 +96,10 @@ cleanup() {
 check_result() {
   local result="$1"
   if [[ "$result" != "0" ]]; then
-    info "TEST FAILED (${result})"
-    cleanup $2
-    exit $result
+    cleanup_test_app
+    TESTSUITE_RESULT=1
   fi
+  return $result
 }
 
 wait_for_cid() {
@@ -240,11 +255,13 @@ test_application() {
   wait_for_cid
 
   test_scl_usage "nginx -v" "nginx version: nginx/$VERSION."
-  check_result $? "test-app"
+  check_result $? || return 1
 
   test_connection
-  check_result $? "test-app"
+  check_result $? || return 1
+
   cleanup_test_app
+  return 0
 }
 
 test_pre_init_script() {
@@ -255,12 +272,13 @@ test_pre_init_script() {
   wait_for_cid
 
   test_command "cat /opt/app-root/etc/nginx.d/default.conf | grep 'resolver' | sed -e 's/resolver\(.*\);/\1/' | grep 'DNS_SERVER'" ""
-  check_result $? "start-hook-test-app"
+  check_result $? || return 1
 
   test_connection_s2i
-  check_result $? "start-hook-test-app"
-  cleanup_test_app
+  check_result $? || return 1
 
+  cleanup_test_app
+  return 0
 }
 
 test_log_output() {
@@ -275,25 +293,24 @@ test_log_output() {
   info "Testing that GET / was logged as 200"
 
   test_for_output "http://$(container_ip):${test_port}/" "NGINX is working"
-  check_result $? "test-app"
+  check_result $? || return 1
 
   test_logs '"GET / HTTP/1.1" 200' 'Test that GET / is logged as 200' stdout
-  check_result $? "test-app"
+  check_result $? || return 1
 
   info "Testing that GET /nothing-at-all was logged as 404"
 
   test_for_output "http://$(container_ip):${test_port}/nothing-at-all" "404"
-  check_result $? "test-app"
+  check_result $? || return 1
 
   test_logs '"GET /nothing-at-all HTTP/1.1" 404' 'Test that bad GET is logged as 404' stdout
-  check_result $? "test-app"
+  check_result $? || return 1
 
   test_logs 'open.*failed.*No such file or directory' 'Test that bad GET is logged to error.log' stdouterr
-  check_result $? "test-app"
-
-  info "Log output tested successfully."
+  check_result $? || return 1
 
   cleanup_test_app
+  return 0
 }
 
 test_log_volume_output() {
@@ -308,25 +325,26 @@ test_log_volume_output() {
   info "Testing that GET / was logged as 200"
 
   test_for_output "http://$(container_ip):${test_port}/" "NGINX is working"
-  check_result $? "test-app"
+  check_result $? || return 1
 
   test_logs '"GET / HTTP/1.1" 200' 'Test that GET / is logged as 200' /var/log/nginx/access.log
-  check_result $? "test-app"
+  check_result $? || return 1
 
   info "Testing that GET /nothing-at-all was logged as 404"
 
   test_for_output "http://$(container_ip):${test_port}/nothing-at-all" "404"
-  check_result $? "test-app"
+  check_result $? || return 1
 
   test_logs '"GET /nothing-at-all HTTP/1.1" 404' 'Test that bad GET is logged as 404' /var/log/nginx/access.log
-  check_result $? "test-app"
+  check_result $? || return 1
 
   test_logs 'open.*failed.*No such file or directory' 'Test that bad GET is logged to error.log' /var/log/nginx/error.log
-  check_result $? "test-app"
+  check_result $? || return 1
 
   info "Log volume output tested successfully."
 
   cleanup_test_app
+  return 0
 }
 
 test_perl_directive() {
@@ -339,13 +357,14 @@ test_perl_directive() {
 
   info "Testing perl_set directive sets header with perl version"
   test_for_output "http://$(container_ip):${test_port}/" "X-Perl-Version: ${perl_version}"
-  check_result $? "perl-test-app"
+  check_result $? || return 1
 
   info "Testing perl directive runs perl location handler"
   test_for_output "http://$(container_ip):${test_port}/perl" "Perl location handler is working"
-  check_result $? "perl-test-app"
+  check_result $? || return 1
 
   cleanup_test_app
+  return 0
 }
 
 test_latest_imagestreams() {
@@ -359,59 +378,59 @@ test_latest_imagestreams() {
   return $result
 }
 
-cid_file=$(mktemp -u --suffix=.cid)
+test_application_user() {
+  # Test application with random uid
+  CONTAINER_ARGS="--user 12345" test_application
+}
 
-# Since we built the candidate image locally, we don't want S2I attempt to pull
-# it from Docker hub
-s2i_args="--pull-policy=never"
+function run_all_tests() {
+  local APP_NAME="$1"
+  for test_case in $TEST_LIST; do
+    info "Running test $test_case ...."
+    if $test_case; then
+      printf -v test_short_summary "${test_short_summary}[PASSED] $test_case\n"
+    else
+      printf -v test_short_summary "${test_short_summary}[FAILED] $test_case\n"
+      [ -n "${FAIL_QUICKLY:-}" ] && echo "$sum" && return 1
+    fi
+  done;
+  cleanup "${APP_NAME}"
+}
 
-prepare "test-app"
-run_s2i_build "test-app"
-check_result $? "test-app"
+function build_image() {
+  local test_name="$1"
+  cid_file=$(mktemp -u --suffix=.cid)
 
-# Verify the 'usage' script is working properly when running the base image with 's2i usage ...'
-test_s2i_usage
-check_result $? "test-app"
+  # Since we built the candidate image locally, we don't want S2I attempt to pull
+  # it from Docker hub
+  s2i_args="--pull-policy=never"
 
-# Verify the 'usage' script is working properly when running the base image with 'docker run ...'
-test_docker_run_usage
-check_result $? "test-app"
+  prepare "${test_name}"
+  run_s2i_build "${test_name}"
+  check_result $?
+}
 
-# Test application with default uid
-test_application
+build_image "test-app"
 
-# Test logging works
-test_log_output
+# Run the chosen tests
+TEST_LIST=${TEST_LIST_APP} run_all_tests "test-app"
 
-# Test logging to volume works
-test_log_volume_output
+build_image "start-hook-test-app"
 
-# Test application with random uid
-CONTAINER_ARGS="--user 12345" test_application
-cleanup "test-app"
+# Run the chosen tests
+TEST_LIST=${TEST_LIST_HOOK_APP} run_all_tests "start-hook-test-app"
 
-# Test start-hook script functionality
-cid_file=$(mktemp -u --suffix=.cid)
+build_image "perl-test-app"
 
-prepare "start-hook-test-app"
-run_s2i_build "start-hook-test-app"
-check_result $? "start-hook-test-app"
+# Run the chosen tests
+TEST_LIST=${TEST_LIST_PERL_APP} run_all_tests "perl-test-app"
 
-test_pre_init_script
-cleanup "start-hook-test-app"
+echo "$test_short_summary"
 
-# Test perl module functionality
-cid_file=$(mktemp -u --suffix=.cid)
+if [ $TESTSUITE_RESULT -eq 0 ] ; then
+  echo "Tests for ${IMAGE_NAME} succeeded."
+else
+  echo "Tests for ${IMAGE_NAME} failed."
+fi
 
-prepare "perl-test-app"
-run_s2i_build "perl-test-app"
-check_result $? "perl-test-app"
-
-test_perl_directive
-
-test_latest_imagestreams
-check_result $?
-
-cleanup "perl-test-app"
-
-info "All tests finished successfully for ${IMAGE_NAME}."
+exit $TESTSUITE_RESULT
