Add tests for logging output. (#76)
* Add tests for logging output.

* Sync logging changes from 1.14/Dockerfile.rhel7.

* Sync with 1.12/1.14 Dockerfile.

* Add some more debugging output.

* Use full path to SCL log directory.

* Use full path to SCL log directory.

* Fix and test NGINX_LOG_TO_VOLUME usage.

* Sync with 1.14.

* Use stdout & stderr consistently, and test for it.

* Check error.log is correct as well.

* Fix log test output stdout/stderr handling.

* Use error.log in test nginx.conf, fixing NGINX_LOG_TO_VOLUME testing.

* Accept stderr output from stdout of "docker logs" as well.

Possible workaround for different behaviour across versions
of docker?  In CI this is failing with the rhscl/*-rhel7
images, both works in Fedora with the CentOS images.

diff --git a/1.12/test/run b/1.12/test/run
--- a/1.12/test/run
+++ b/1.12/test/run
@@ -6,7 +6,8 @@
 # IMAGE_NAME specifies a name of the candidate image used for testing.
 # The image has to be available before this script is executed.
 #
-IMAGE_NAME=${IMAGE_NAME:-rhscl/nginx-112-rhel7}
+test -n "${IMAGE_NAME-}" || false 'make sure $IMAGE_NAME is defined'
+test -n "${VERSION-}" || false 'make sure $VERSION is defined'
 
 # TODO: Make command compatible for Mac users
 test_dir="$(readlink -zf $(dirname "${BASH_SOURCE[0]}"))"
@@ -54,6 +55,7 @@ prepare() {
 
 run_test_application() {
   run_args=${CONTAINER_ARGS:-}
+  info "Running docker run --user=100001 ${run_args} --cidfile=${cid_file} ${IMAGE_NAME}-${1}"
   docker run --user=100001 ${run_args} --cidfile=${cid_file} ${IMAGE_NAME}-${1}
 }
 
@@ -144,6 +146,34 @@ test_command() {
   return 0
 }
 
+test_logs() {
+  local expected="$1"
+  local message="$2"
+  local logfile="$3"
+
+  if [ "$message" ]; then
+    info ${message}
+  fi
+  if [ "x$logfile" = "xstdouterr" ]; then
+      out=$(docker logs $(cat ${cid_file}) 2>&1)
+  elif [ "x$logfile" = "xstdout" ]; then
+      out=$(docker logs $(cat ${cid_file}) 2>/dev/null)
+  elif [ "x$logfile" = "xstderr" ]; then
+      out=$(docker logs $(cat ${cid_file}) 2>&1 1>/dev/null)
+  elif [ -n "$logfile" ]; then
+      info "Extracting $logfile via docker cp..."
+      out=$(docker cp $(cat ${cid_file}):${logfile} - | tar -xO '*')
+  else
+      out=$(docker logs $(cat ${cid_file}) 2>&1)
+  fi
+  if ! echo "${out}" | egrep -q "${expected}"; then
+    echo "ERROR[docker logs $logfile] Expected '${expected}', got '${out}'"
+    return 1
+  fi
+
+  return 0
+}
+
 test_for_output()
 {
   local url="$1"
@@ -210,7 +240,7 @@ test_application() {
   # Wait for the container to write it's CID file
   wait_for_cid
 
-  test_scl_usage "nginx -v" "nginx version: nginx/1.12."
+  test_scl_usage "nginx -v" "nginx version: nginx/$VERSION."
   check_result $? "test-app"
 
   test_connection
@@ -234,19 +264,85 @@ test_pre_init_script() {
 
 }
 
+test_log_output() {
+  info "Testing log output for $IMAGE_NAME"
+
+  # Verify that the HTTP connection can be established to test application container
+  run_test_application "test-app" &
+
+  # Wait for the container to write it's CID file
+  wait_for_cid
+
+  info "Testing that GET / was logged as 200"  
+
+  test_for_output "http://$(container_ip):${test_port}/" "NGINX is working"
+  check_result $? "test-app"
+
+  test_logs '"GET / HTTP/1.1" 200' 'Test that GET / is logged as 200' stdout
+  check_result $? "test-app"
+
+  info "Testing that GET /nothing-at-all was logged as 404"  
+
+  test_for_output "http://$(container_ip):${test_port}/nothing-at-all" "404"
+  check_result $? "test-app"
+
+  test_logs '"GET /nothing-at-all HTTP/1.1" 404' 'Test that bad GET is logged as 404' stdout
+  check_result $? "test-app"
+
+  test_logs 'open.*failed.*No such file or directory' 'Test that bad GET is logged to error.log' stdouterr
+  check_result $? "test-app"
+
+  info "Log output tested successfully."
+  
+  cleanup_test_app
+}
+
+test_log_volume_output() {
+  info "Testing log volume output for $IMAGE_NAME"
+
+  # Verify that the HTTP connection can be established to test application container
+  CONTAINER_ARGS="-e NGINX_LOG_TO_VOLUME=y" run_test_application "test-app" &
+
+  # Wait for the container to write it's CID file
+  wait_for_cid
+
+  info "Testing that GET / was logged as 200"  
+
+  test_for_output "http://$(container_ip):${test_port}/" "NGINX is working"
+  check_result $? "test-app"
+
+  test_logs '"GET / HTTP/1.1" 200' 'Test that GET / is logged as 200' /var/log/nginx/access.log
+  check_result $? "test-app"
+
+  info "Testing that GET /nothing-at-all was logged as 404"  
+
+  test_for_output "http://$(container_ip):${test_port}/nothing-at-all" "404"
+  check_result $? "test-app"
+
+  test_logs '"GET /nothing-at-all HTTP/1.1" 404' 'Test that bad GET is logged as 404' /var/log/nginx/access.log
+  check_result $? "test-app"
+
+  test_logs 'open.*failed.*No such file or directory' 'Test that bad GET is logged to error.log' /var/log/nginx/error.log
+  check_result $? "test-app"
+
+  info "Log volume output tested successfully."
+
+  cleanup_test_app
+}
+
 cid_file=$(mktemp -u --suffix=.cid)
 
 # Since we built the candidate image locally, we don't want S2I attempt to pull
 # it from Docker hub
 s2i_args="--pull-policy=never"
 
-if [ "$TARGET" == "fedora" ]; then
+if [ "$TARGET" == "fedora" ] || [ "$TARGET" == "rhel8" ]; then
   mv ${test_dir}/test-app/nginx.conf{,.bkp}
   cp ${test_dir}/test-app/nginx.conf{.fedora,}
 fi
 prepare "test-app"
 run_s2i_build "test-app"
-if [ "$TARGET" == "fedora" ]; then
+if [ "$TARGET" == "fedora" ] || [ "$TARGET" == "rhel8" ]; then
   mv ${test_dir}/test-app/nginx.conf{.bkp,}
 fi
 check_result $? "test-app"
@@ -262,6 +358,12 @@ check_result $? "test-app"
 # Test application with default uid
 test_application 
 
+# Test logging works
+test_log_output
+
+# Test logging to volume works
+test_log_volume_output
+
 # Test application with random uid
 CONTAINER_ARGS="--user 12345" test_application
 cleanup "test-app"
@@ -276,4 +378,4 @@ check_result $? "start-hook-test-app"
 test_pre_init_script
 cleanup "start-hook-test-app"
 
-info "All tests finished successfully."
+info "All tests finished successfully for ${IMAGE_NAME}."
